[package]
name = "k8s_node_server"
version = "0.1.0"
edition = "2024"

[dependencies]
# 사용자가 요청한 버전을 유지합니다.
kube = "1.1.0"
k8s-openapi = { version = "0.25", features = ["v1_30"] }

# Actix 웹 서버 및 웹소켓
actix = "0.13"
actix-web = "4"
actix-web-actors = "4"
actix-files = "0.6"

# JSON 직렬화 및 로그
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
env_logger = "0.10"

# 유틸리티
rand = "0.8"
tokio = { version = "1", features = ["full"] }




