[package]
name = "k8s_node_server"
version = "0.1.0"
edition = "2024"

[dependencies]
# 사용자가 요청한 버전을 유지합니다.
kube = "1.1.0"
k8s-openapi = { version = "0.25", features = ["v1_30"] }
actix = "0.13"
actix-web = "4.0"
actix-web-actors = "4.0"
actix-cors = "0.6"
actix-files = "0.6"
#kube = "0.87"
#k8s-openapi = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.10"
log = "0.4"





