[package]
name = "k8s_node_server"
version = "0.1.0"
edition = "2024"

[dependencies]
kube = "1.1.0" # Kubernetes API 클라이언트
k8s-openapi = { version = "0.25", features = ["v1_30"] } # Kubernetes API 모델 (버전은 사용하는 K8s 클러스터에 맞게 조정)
actix = "0.13"
actix-web = "4"
actix-web-actors = "4"
actix-cors = "0.6"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
tokio = { version = "1", features = ["full"] }

