[package]
name = "k8s_node_server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13" # actix 액터 프레임워크
actix-web = "4" # 웹 서버 프레임워크
actix-web-actors = "4" # actix-web과 actix 액터 통합 (웹소켓)
actix-cors = "0.6" # CORS 미들웨어
actix-files = "0.6" # 정적 파일 서빙
kube = "0.89" # Kubernetes API 클라이언트
k8s-openapi = { version = "0.19", features = ["v1_27"] } # Kubernetes API 모델 (버전은 사용하는 K8s 클러스터에 맞게 조정)
serde = { version = "1.0", features = ["derive"] } # 직렬화/역직렬화
serde_json = "1.0" # JSON 처리
log = "0.4" # 로깅
env_logger = "0.10" # 로깅 구현체
tokio = { version = "1", features = ["full"] } # 비동기 런타임 (actix-web 4버전 사용 시 필요)

